### ISSUE TITLE
v0.94.0 regression: bignum too big to convert into `long' (RangeError)

### ISSUE THREAD

**Issue by landongrindheim** [excon/excon#800] opened 2022-11-29 13:53 UTC
## 🖼️ Context

My team recently upgraded from v0.93.1 to v0.94.0 and began experiencing errors being raised when making requests. This hasn't been happening on every request. It has been happening sporadically enough that it took a couple weeks to identify Excon as the source of the error. After reverting to use v0.93.1 we are no longer experiencing any issues.

## 📝 Notes

I looked through the commits that make up the changes for v0.94.0 and noticed that, as of https://github.com/excon/excon/commit/7ac35684d667a6f206431be93aa6e2fb9a6d07e6, `max_length` is handled differently in `Socket#read_nonblock`. This value (`max_length`) is later given to `String#slice!`, which raises the error we've been experiencing. While it seems likely, I haven't determined for certain that this is the cause of the regression.

**Before:**
```ruby
        if max_length
           until @read_buffer.length >= max_length
             @read_buffer << @socket.read_nonblock(max_length - @read_buffer.length)
           end
```

**After:**
```ruby
       while !@backend_eof && (!max_length || @read_buffer.length < max_length)
           @read_buffer << @socket.read_nonblock(@data[:chunk_size])
```

#### 🔎 Stack trace

```plaintext
Excon::Error::Socket: bignum too big to convert into `long' (RangeError)
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/socket.rb:221:in `slice!'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/socket.rb:221:in `read_nonblock'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/socket.rb:58:in `read'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/response.rb:133:in `parse'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/middlewares/response_parser.rb:7:in `response_call'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/connection.rb:456:in `response'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/connection.rb:287:in `request'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/middlewares/idempotent.rb:50:in `error_call'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/middlewares/base.rb:17:in `error_call'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/middlewares/base.rb:17:in `error_call'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/connection.rb:312:in `rescue in request'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/connection.rb:227:in `request'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/middlewares/idempotent.rb:50:in `error_call'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/middlewares/base.rb:17:in `error_call'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/middlewares/base.rb:17:in `error_call'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/connection.rb:312:in `rescue in request'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon/connection.rb:227:in `request'
  from /usr/local/bundle/gems/excon-0.94.0/lib/excon.rb:250:in `get'
```

**Comment by geemus** [comment] 2022-11-29 14:04
Sorry to hear about your troubles here, we had hoped it to be relatively safe, but have started hearing about some issues.

@vasi-stripe here is another intermittent issues, let me know if you have ideas and/or how I can help.

**Comment by geemus** [comment] 2022-11-30 13:56
@landongrindheim I was trying to survey a bit to see if I could see other folks with similar problems for inspiration. Any chance you are running in jruby? I saw a few mentions of similar errors and was trying to figure out if that would be good to dig deeper into or if it was a false lead.

**Comment by landongrindheim** [comment] 2022-11-30 14:42
We're not running JRuby. From `gem env`:

```plaintext
RUBY VERSION: 3.1.2 (2022-04-12 patchlevel 20) [x86_64-linux]
```

**Comment by geemus** [comment] 2022-11-30 14:54
@landongrindheim K, thanks. Thought it would be good to at least narrow that down.

**Comment by geemus** [comment] 2022-11-30 15:12
Digging a little deeper, I at least have an initial hypothesis to share. From the stack trace it looks like the failure case related to chunked encoding in particular, which should include a chunk size which is then read. I think with the revisions in 0.94.0 we introduced this regression because some of the reads were made to be more aggressive and buffer. I suspect this may result in a case where we inadvertently read something that isn't intended to be a chunk size, convert it to an int and then try to do a read. I haven't definitively confirmed that yet though. Also, I don't think chunked encoding usage is necessarily the most common in the wild, which may explain why this was happening only infrequently. I'll try to dig deeper soon, but need to step away for child care duties (family unfortunately got covid over Thanksgiving). I think this gives me some ideas on how/where to look more, but not quite sure when I'll have time/bandwidth to do so. Certainly welcome further ideas and feedback if folks have them. Thanks!

**Comment by landongrindheim** [comment] 2022-11-30 20:17
> I suspect this may result in a case where we inadvertently read something that isn't intended to be a chunk size, convert it to an int and then try to do a read.

I spent a little more time tracing through some code and came to a the same conclusion 🙂 In our case this error is happening where we're handling a bunch of Git metadata. I can imagine a case where a SHA or some other blob is being cast to a very large number. 👇 is the chunk of code I see that potentially happening in.


https://github.com/excon/excon/blob/962956f26c8ce6a9e0ac293dfc2db4db5fc79051/lib/excon/response.rb#L131-L142

**Comment by geemus** [comment] 2022-11-30 21:59
@landongrindheim Yeah, something like that is definitely what I was imagining. Thanks for the extra info. I'll try to circle back soon and hopefully in the mean time the earlier version should work to fill the gap.

**Comment by geemus** [comment] 2022-12-08 00:12
@landongrindheim - I think this commit might help, but it's hard to know without a clear repro case: https://github.com/excon/excon/commit/912045d0b91731520d68118f0a5ffce2a16aa713. Any confirmation or further information you can garner from that would be most appreciated.

**Comment by geemus** [comment] 2022-12-08 00:34
P.S. The other commits on master should be safe/unrelated, so you should be able to test from there (rather than needing to cherry pick or something).

**Comment by geemus** [comment] 2022-12-12 15:08
I released v0.95.0 this morning, which fixed the other regression. I'm hoping it fixes this one as well, but am unable to easily confirm. Do let me know if you continue to have problems (and/or if you don't and we can close this). Thanks!

**Comment by landongrindheim** [comment] 2022-12-12 15:21
@geemus Thanks for digging into and addressing this 🙇 I'll try to update and test this this week and will report back with what I find 😄

**Comment by geemus** [comment] 2022-12-13 13:54
@atomgiant Thanks for the additional info, hopefully this resolves it for you, but do let me know if you still see problems.

**Comment by atomgiant** [comment] 2022-12-14 14:23
@geemus I believe v0.95 fixed this issue for me. I've been running v0.95 live in production for about a day with no issues. The v0.94 release caused hundreds of exceptions over a similar timeframe. Thanks for fixing this!

**Comment by geemus** [comment] 2022-12-14 14:47
@atomgiant Awesome, so glad to hear it. Thanks for testing and reporting it back to help us confirm. Since it was intermittent at best I was worried I might miss it and/or introduce other issues, especially without a good reproduction case to work off of. Seemed like it was worth a shot though, and it's definitely a relief to hear that it seems to be working for folks so far.

I'll go ahead and close this out since all reports seem to be positive, but do please comment/reopen (or create a new issue) if anyone runs into further similar issues.

**Closed by geemus** 2022-12-14 14:47 UTC
