### ISSUE TITLE
Intermittent "broken pipe" errors

### ISSUE THREAD

**Issue by paulvwarner** [excon/excon#641] opened 2017-08-29 20:01 UTC
I'm using Carrierwave 1.1.0, Fog 1.41.0, Excon 0.58.0 to upload files to Rackspace from a Ruby on Rails server. I've been seeing "Broken Pipe" errors happening intermittently at the point the code tries these file uploads. I see it a few times a week, but it isn't something I've been able to reproduce locally, because it happens relatively rarely.

The only information I've seen about this type of error online is that it often happens because people aren't pointing to the correct region when trying to upload files, but the region in my config (IAD) matches what the Rackspace site tells me to use.

My Carrierwave config (minus username, API key, fog_directory) looks like this:

```
CarrierWave.configure do |config|
  config.fog_provider = "fog/rackspace/storage" 
  config.fog_credentials = {
      provider: 'Rackspace',
      rackspace_username: 'XXXX',
      rackspace_api_key: 'XXXX',
      rackspace_region: :iad
  }
  config.fog_directory = 'XXXX'
end
```

The error messages I get look like this:
!ruby/exception:Excon::Error::Socket
message: Broken pipe (Errno::EPIPE)
socket_error: !ruby/exception:Errno::EPIPE
message: Broken pipe

I turned on Excon debug logging, and it looks like in the error case Excon tries the request several times and then shows the broken pipe message.  The total time from request start to error message is less than 2 seconds, so I doubt this is a timeout issue with Rackspace, but I don't see any info in the Excon output or other logs that explain why it's retrying or failing.

I've tried a few different versions of Carrierwave and Fog and haven't found a configuration that solves this.  Is there a way I can get more information about what's going on at the point the Excon request to Rackspace happens, or have other people run into this?

**Comment by geemus** [comment] 2017-08-29 20:41
I'm not aware of this being a problem for others, or at least haven't heard about it.

I know in some of my earlier testing against Rackspace it would drop your connection after about 30 seconds or so (whether you were actively making requests or not). It doesn't really sound like that is the case here though, as it fails quickly. Is it possible that the files are particularly large or otherwise anomalous? Just wondering if the server might be responding to files of some particular disposition, rather than just failing on particular files by chance.

Sorry I can't be more directly helpful, but I'm happy to discuss further and try to find a solution for you.

**Comment by vshvedov** [comment] 2017-08-29 20:44
Same here. It seems to be happening with larger files more frequently, but generally, it's the same carriervawe/fog-rackspace/Broken pipe (Errno::EPIPE) behavior.

**Comment by paulvwarner** [comment] 2017-08-29 21:03
For me, it's happening for image uploads where I'm constraining the dimensions of the image it's possible to upload, so the file size doesn't get too crazy - it's usually between 300 and 800 KB.  

I was wondering if Excon is getting a response when it's doing these retries - I don't see it in the output.  (I attached an example of the Excon output for a failure, with the request body and auth info removed.)  If there's a response coming from Rackspace in these cases, I can probably take that to Rackspace and see if they have more info.

[excon request.txt](https://github.com/excon/excon/files/1261734/excon.request.txt)

**Comment by vshvedov** [comment] 2017-08-29 21:14
@paulvwarner could you please share Rackspace's answer after?

**Comment by geemus** [comment] 2017-08-30 13:46
Hmm.

Makes me think we should set an error key in the data for the retries (otherwise you only get to see which error occurred for the last one, rather than the error that led to a particular retry). Does that make sense? I think that would be a worthwhile patch, which might help us narrow things down, but it wouldn't give us response bodies.

That said, I believe retries are only going to show up for requests that fail. So here, my interpretation of those logs would be that when trying to make the initial request an error is raised (probably the broken pipe indicating that the server has closed the socket), so it fails before any response would be available.

Is there any chance that other operations are opening a socket prior to this, which this would then try to re-use? IE anything on the same thread/process that would be doing lookups of existing data? That's the only other thing I can think of (as if it is trying to re-use that socket, it could have a race condition between when that finishes and the write begins). I had thought that for rackspace I made it always use new sockets though, as I'd run into issues similar to what you are seeing if I tried to reuse sockets.

**Comment by paulvwarner** [comment] 2017-08-30 15:57
@geemus I actually have a pretty good log of an error case from this morning, where there were a very small amount of Rackspace requests between authentication and this broken pipe error.  If there's a reused socket involved, I think this would be the most simple case where it could happen.  

Here's the order of events, where this is the first Rackspace file service activity to occur this morning.  

**I assume these are done by fog or carrierwave, maybe because the server was idle for a while**
token 1 - HEAD request to root upload directory - gets 401 response
token 1 - POST request to authenticate into Rackspace  - gets 200 response containing token 2
token 2 - HEAD request to root upload directory - 204 response
token 2 - HEAD request to root upload directory - 204 response
token 2 - HEAD request to root upload directory - 204 response
token 2 - HEAD request to root upload directory - 204 response
token 2 - HEAD request to root upload directory - 204 response
token 2 - HEAD request to root upload directory - 204 response
token 2 - HEAD request to root upload directory - 204 response
token 2 - HEAD request to root upload directory - 204 response

**these are the upload requests - I put code in to retry the upload 3 times if it fails because of a broken pipe - that's why it happens 4 times. The Broken Pipe error was happening before I put in my retry code, though.**
token 3 - PUT request to upload file - tries 4 times then gets "Broken pipe"
token 3 - PUT request to upload file - tries 4 times then gets "Broken pipe"
token 3 - PUT request to upload file - tries 4 times then gets "Broken pipe"
token 3 - PUT request to upload file - tries 4 times then gets "Broken pipe"

**this looks like something that carrierwave or fog did automatically**
POST request to authenticate into Rackspace  - gets 200 response


I think all of these except the last authentication POST request are occurring on the same process.  The log messages that contain all the other Excon requests are all prefixed with "App 27913 stderr".  I think 27913 is the process id.  

I noticed that the failed PUT requests are using a different x-auth-token (token 3) from the token returned by the newest authentication to Rackspace from this morning (token 2).  Looking back through the Excon logs, the possibly no-longer-valid token #3 got returned by an authentication call from yesterday, and those requests are also logged with the prefix "App 27913 stderr".  

I'm running a production Rails server and a staging Rails server from this same Rackspace server, and both Rails servers authenticate to this same Rackspace file service, so I wonder if when one environment authenticates, it invalidates the auth token of the other environment.  I could try hosting the environments on separate servers or point them to different Rackspace file service accounts.  

Do you know of any other reasons that token thing could be happening, or if it's actually a problem?  It might also be that separate processes in the same environment are authenticating to Rackspace separately and messing each other up.  

If you want to see the actual Excon logs, please let me know - I can remove the auth info and attach them.

**Comment by paulvwarner** [comment] 2017-08-30 17:31
@vshvedov sure - if I hear back from Rackspace with something useful, I'll put that info here.

**Comment by paulvwarner** [comment] 2017-08-31 21:03
I changed my stuff so that my production environment uses its own user and API key to authenticate to the Rackspace API, so I'm confident the issue is not that different environments are messing up each other's auth tokens by authenticating with the same user at different times.  However, this broken pipe error occurred again in production after I made that change.  

This time, I noticed in the Excon logs that things happened in this order:

1 - process A authenticates to Rackspace API with prod credentials and gets token XX.
2 - process A authenticates to Rackspace API with prod credentials and gets token YY.
3 - process B authenticates to Rackspace API with prod credentials and gets token ZZ.
4 - process A attempts a PUT request to the Rackspace API using token XX and gets a broken pipe error.

So in this case the error happened when process A attempted a PUT request to Rackspace with an old token.  It isn't the latest token generated for the prod credentials, and it isn't the latest token generated on process A.  Unless Rackspace allows multiple authentication tokens to be valid for the same user at the same time, I wonder if that causes this.  I do see cases where use of an incorrect token generates a 401 response from Rackspace instead of nothing, though, so I'm not sure.

So I have a couple questions (maybe for @geemus?):
1) do you think this token thing could be the problem?
2) do you know if there's a way I can force fog to re-authenticate every time a fog operation needs to happen, or some other brute-force-y way I can work around this using config options?

Thanks!

**Comment by vshvedov** [comment] 2017-08-31 21:11
There's an interesting behavior reported by one of our people, who initially reported about the issue. If he gets the broken pipe, there's a 75% chance he hits it again 5-10x, during attempts to re-upload an image directly after the exception.

**Comment by geemus** [comment] 2017-08-31 21:32
Given what you both describe, I could certainly imagine a bad token being the issue. In particular, I wouldn't expect other socket issues to be persistent. If you reset the socket and retry, the retry should theoretically work. That it continues to fail makes it seem more likely it is something that remains constant (and token sounds like a good candidate).

I don't know the context by which it was added (it may well have been something like this), but it appears fog-rackspace has an `rackspace_must_reauthenticate` option, that if you set it to true, it will always get a new token. I suspect this will cause performance impact, but if that is acceptable it might work more consistently.

https://github.com/fog/fog-rackspace/blob/master/lib/fog/rackspace/storage.rb#L57

**Comment by paulvwarner** [comment] 2017-08-31 21:38
Thanks, @geemus, I'll give that a try!

**Comment by geemus** [comment] 2017-09-01 15:21
Sure thing, didn't even remember/realize it was a thing until you described it. It seems like a awfully big coincidence to be unrelated, so hopefully it clears things up for you. That said, it sounds like it might point to a bug in Rackspace's implementation (it would be much easier for us to recover/re-auth to a 400-series error than to guess that a this is what a particular broken pipe might mean). So perhaps with this info they can also improve the error handling with invalid tokens as well.

**Comment by vshvedov** [comment] 2017-09-12 11:28
Re-authentification doesn't help. At least on my end. Any progress with this on your side @paulvwarner ?

**Comment by paulvwarner** [comment] 2017-09-12 13:58
@vshvedov @geemus I also am still getting this error after trying the `rackspace_must_reauthenticate` option.  I made the following monkey patch to hardcode `rackspace_must_reauthenticate` to true, since in the version of Fog I'm using it looks like that is hardcoded to false and not available for override with passed parameters.

`
module Fog
  module Storage
    class Rackspace < Fog::Service
      module Common
        def apply_options(options)
          @rackspace_api_key = options[:rackspace_api_key]
          @rackspace_username = options[:rackspace_username]
          @rackspace_cdn_ssl = options[:rackspace_cdn_ssl]
          @rackspace_auth_url = options[:rackspace_auth_url]
          @rackspace_servicenet = options[:rackspace_servicenet]
          @rackspace_auth_token = options[:rackspace_auth_token]
          @rackspace_storage_url = options[:rackspace_storage_url]
          @rackspace_cdn_url = options[:rackspace_cdn_url]
          @rackspace_region = options[:rackspace_region]
          @rackspace_temp_url_key = options[:rackspace_temp_url_key]
          @rackspace_must_reauthenticate = true
          @connection_options = options[:connection_options] || {}

          unless @rackspace_region || (@rackspace_storage_url && @rackspace_cdn_url)
            Fog::Logger.deprecation("Default region support will be removed in an upcoming release. Please switch to manually setting your endpoint. This requires settng the :rackspace_region option.")
          end

          @rackspace_region ||= :dfw
        end
      end
    end
  end
end
`

... but yeah.  It does seem to trigger more authentications, but the broken pipe error can still happen.

The latest broken pipe error request from 9/11 was attempting to use an auth token that got returned from an auth request on 9/7, and there were several authentications that happened between that time on 9/7 and on 9/11 when the error happened.  That seems to be something it shouldn't be trying to do - it should be using whatever the latest token received from the API is, right?  

In my ticket with Rackspace about this, they weren't able to find the incoming request on 9/11 that caused the broken pipe error.  My understanding of broken pipe errors is that they happen when a socket connection between two peers is closed, but one of the peers (my server, in this case) attempts to use that socket connection after it's closed.  Since I think that means the error is saying that a connection to the Rackspace server isn't available anymore, I don't think I'll ever receive a response from Rackspace. That, paired with Excon sending an obsolete token in the error cases I've seen, makes me think this is an error somewhere in Fog or Excon, not an error with Rackspace, since Rackspace seems to not even be receiving the request.  

Anyone have any ideas?

**Comment by geemus** [comment] 2017-09-12 14:44
There remains, unfortunately, a kind of in-between case. Your description of the error matches with my understanding, but it is possible that the error happens in the middle of a request in-progress (rather than at the beginning). So, for instance, it's possible that we would start writing to the socket and the server might read the headers and then close the socket. This might result in it not being logged normally as well (or not). It's kind of hard to say without being able to dig into network info.

I would agree that it seems surprising that the old 9/7 token would still be in use, especially with the reauth stuff setup. As you suggest, if the reauth stuff is on it should use the latest token instead of a cached one (if I understand correctly). That said, as I continue to dig in, I do see one place where it might still be problematic.

When the connection is initialized it tries to cache a token, which it then uses when it attempts to connect. Then, if it fails to auth it will get a new token and try again. See:

https://github.com/fog/fog-rackspace/blob/690134acfdef6eaa75d88021e24fd93b08a2ee7b/lib/fog/rackspace/service.rb#L39-L52

That would mean that the connection/token will get setup when the server boots, and if it is days before an upload occurs, it will not refresh until it fails. And then ONLY if it fails as an unauthorized error, which in your case it is not. If we just got unauthorized errors from stale tokens, it would be fine (you would just refresh your token as needed). But if those requests are resulting in broken pipes, it is a different matter. We could test this by monkey-patching the request method to also rescue broken pipes there and retry. If the errors disappear we can probably assume that we were more-or-less on the right track anyway. What do you think?

**Comment by paulvwarner** [comment] 2017-09-12 15:05
Thanks, @geemus, that works for me - I'll try that.  It looks like this might be the method I'd patch, and I'd do something like the below to make broken pipe errors trigger the same behavior as a 401.  Does this look like an okay place to do the patch to you?

```
module Fog
  module Compute
    class Cloudstack < Fog::Service
      class Real
        private
        def issue_request(params={},headers={},method='GET',expects=200)
          begin
            @connection.request({
                                    :query => params,
                                    :headers => headers,
                                    :method => method,
                                    :expects => expects
                                })

          rescue Excon::Errors::HTTPStatusError => error
            error_response = Fog::JSON.decode(error.response.body)

            error_code = error_response.values.first['errorcode']
            error_text = error_response.values.first['errortext']

            case error_code
              when 401
                raise Fog::Compute::Cloudstack::Unauthorized, error_text
              when 431
                raise Fog::Compute::Cloudstack::BadRequest, error_text
              else
                if error_text.to_s.downcase.include?('broken pipe')
                  raise Fog::Compute::Cloudstack::Unauthorized, error_text
                else
                  raise Fog::Compute::Cloudstack::Error, error_text
                end
            end
          end
        end
      end
    end
  end
end
```

**Comment by paulvwarner** [comment] 2017-09-12 15:14
@geemus, sorry, I see the place where I should probably change this in the gist you linked... I'll try there.

**Comment by geemus** [comment] 2017-09-12 16:54
@paulvwarner sounds good, just let me know if you need further guidance.

**Comment by vshvedov** [comment] 2017-09-14 19:46
Not yet 100% confirmed, but it seems, that rescuing the `Errno::EPIPE` helps.

**Comment by paulvwarner** [comment] 2017-09-15 14:14
Yeah - I see a case where it worked in my logs!  The broken pipe error happened, then the retry with new authentication succeeded.  I'm going to take out the `rackspace_must_reauthenticate` monkey patch and make sure the broken pipe catching stuff still works.

**Comment by geemus** [comment] 2017-09-15 14:48
Awesome, glad to hear it sounds like we are making progress on this one (since it was pretty tricksy). Seems like it would be good to patch up into fog-rackspace, but if you don't mind running it a bit longer to help us gain a bit more confidence I would appreciate it. Thanks!

**Comment by vshvedov** [comment] 2017-09-15 20:34
Unfortunately, I just faced the exception again. I'll raise the number of retries to see how this works (slower is still better than this, anyway).

**Comment by codeodor** [comment] 2017-09-20 11:54
Just wanted to chime in and say I'm facing this too, and it seems to have only started recently. I don't recall any changes that would have coincided though. I did upgrade to Rails 5.1 about a month ago, but I didn't start seeing the errors until last week.  (That said, uploads in this app are seasonal-ish, so it could be that no one was uploading until last week).

The Rails 5.1 upgrade also upgraded:

excon 0.45.2 -> 0.58
fog 1.29.0 -> 1.41.0
fog-rackspace not present? -> 0.1.5
carrierwave 0.10.0 -> 1.1.0

**Comment by vshvedov** [comment] 2017-09-20 12:05
Just as the part of experimenting with the issue, I have increased the number of retries up to ten. Same story. I have a feeling that something else raises the `Errno::EPIPE` exception.

**Comment by vshvedov** [comment] 2017-09-20 12:08
Btw, Rackspace just closed my ticket with the question and ignored to comment about any related changes in their API, same as ignored my request for account-related logs for a period of time when I definitely have the Errno::EPIPE.

**Comment by codeodor** [comment] 2017-09-22 16:00
@paulvwarner are you still seeing the issue after the changes you made?

**Comment by paulvwarner** [comment] 2017-09-22 16:09
I made a change to retry the upload on broken pipe errors on Sept 12 and since then have only seen the broken pipe error happen twice, but the new change's retry succeeded both times.  My monkey patch looks like this (I put this in a file at config/fog_overrides.rb):

```
module Fog
  module Rackspace
    class Service
      def request(params, parse_json = true)
        first_attempt = true
        begin
          response = @connection.request(request_params(params))
        rescue Excon::Errors::Unauthorized => error
          raise error unless first_attempt
          first_attempt = false
          authenticate
          retry
        rescue Excon::Error::Socket => ees
          if ees.message && ees.message.downcase.include?('broken pipe')
            raise ees unless first_attempt
            first_attempt = false
            authenticate
            retry
          end
        end

        process_response(response) if parse_json
        response
      end
    end
  end
end
```

**Comment by codeodor** [comment] 2017-09-22 16:18
Thanks! I'm going to try that.

Just for everyone else's sake, I saw this error for the first time this morning (have not yet made any changes):

`#<Fog::Storage::Rackspace::ServiceError: [HTTP 401 | tx4ed768288b984a1e8cef0-0059c52547dfw1] <html><h1>Unauthorized</h1><p>This server could not verify that you are authorized to access the document you requested.</p></html>>`

I think it must be related, and I wonder if they're just having a lot of issues right now.

**Comment by geemus** [comment] 2017-09-25 19:41
Thanks for the updates, if this continues to look good, we should certainly see about getting the change into the fog-rackspace code directly so you can get rid of the patches. Thanks!

**Comment by codeodor** [comment] 2017-09-25 20:34
Rackspace said:

> We should be able to track the object if you have the X-Trans-ID on one of the failed uploads from your previous attempts. You should be able to get this information from the HTTP response header on the call you issued to the api.

> https://developer.rackspace.com/docs/cloud-files/v1/storage-api-reference/object-services-operations/#create-or-update-object

I don't happen to have any logs with this, and since making the change above I haven't noticed any errors, but in case someone has some logs or runs into this before making any changes, I thought you'd like to know.

**Comment by codeodor** [comment] 2017-10-03 17:10
We've had probably 100 successful uploads since then, and no failures. I wish I had the guts to remove the "fix" and see if we start seeing failures again, but I'm happy enough to leave it and consider the issue fixed.

I think it's worth moving it into the fog-rackspace project for a permanent fix.

**Comment by geemus** [comment] 2017-10-03 19:14
@codeodor understandable. Yeah, I think it should be a pretty safe change (probably not going to make anything worse anyway). Would you be able to do the honors of making a PR for us? Thanks!

**Comment by duskhacker** [comment] 2017-10-20 15:20
Got here researching what appears to be the same issue. Will try the monkey patch and report back.

**Comment by mateomurphy** [comment] 2018-07-25 20:31
Just ran into this issue, has the monkey patch been successful in resolving it?

**Comment by codeodor** [comment] 2018-07-26 18:34
We have never ran into the issue again after applying the fix.

**Comment by geemus** [comment] 2018-07-26 20:52
I'm going to go ahead and close, as in rereading (if I'm not mistaken) it is really a rackspace/fog-rackspace issue more than an excon one per se? I'd still be happy to support a patch on fog-rackspace if anyone wants to work on that though. Thanks!

**Closed by geemus** 2018-07-26 20:52 UTC

**Comment by codeodor** [comment] 2018-07-27 14:32
@geemus is it rackspace/fog-rackspace or fog/fog-rackspace?  If the former, I guess I need to look for that, but if the latter, I did open a fix at https://github.com/fog/fog-rackspace/pull/26, and would appreciate any support you can give to get it merged.

**Comment by geemus** [comment] 2018-07-30 13:36
@codeodor fog/fog-rackspace should be the place. Sorry, I guess I must have missed that.
