### ISSUE TITLE
An unmade request can cause tests with stubs to spuriously pass

### ISSUE THREAD

**Issue by jkakar** [excon/excon#179] opened 2013-01-13 06:15 UTC
I'm using the stub functionality built in to Excon and I really like
it.  Having this functionality be a first-class citizen is super
awesome, especially in this kind of library.  One small issue I have
is that, in some cases, tests can spuriously pass if an expected
request is not made.

For example, consider this application code that might represent a
client library that makes fire-and-forget calls to an API:

``` ruby
def make_request()
  connection = Excon.new('http://example.com')
  connection.post(path: '/path')
end
```

And the accompanying test logic:

``` ruby
def setup
  super
  Excon.stubs.clear
  Excon.defaults[:mock] = true
end

def test_make_request
  Excon.stub(method: :post) do |request|
    assert_equal('/path', request[:path])
    {status: 200}
  end
  make_request
end
```

I expect this test to fail if the code in `make_request` is commented
out completely, but it doesn't.  The `Excon.stub` block simply never
gets called.  My workaround, for now, is to add an `Excon.stubs.pop`
call to the test:

``` ruby
def test_make_request
  Excon.stub(method: :post}) do |request|
    assert_equal('/path', request[:path])
    Excon.stubs.pop
    {status: 200}
  end
  make_request
end
```

And then, in `teardown`, ensure that all stubs have been consumed:

``` ruby
def teardown
  assert Excon.stubs.empty?
  super
end
```

This is okay, but it's also error-prone because I may forget a call to
`Excon.stubs.pop` and I also have to be careful to pop from the front
of the `Excon.stubs` array and not the end because of the way it works
internally.  It'd be nice if there was a method to confirm that all
expected requests were made, something like:

``` ruby
def teardown
  Excon.verify
  super
end
```

**Comment by geemus** [comment] 2018-07-30 19:54
Closing as duplicate of #434.

**Closed by geemus** 2018-07-30 19:54 UTC
Labels: wontfix
