### ISSUE TITLE
Shindo tests hang (run indefitely) on random test

### ISSUE THREAD

**Issue by pvalena** [excon/excon#733] opened 2021-01-07 00:51 UTC
it hangs (livelock) on, f.e.:

```
DEBUG: + shindont
DEBUG:
DEBUG:   Excon bad server interaction +++++
DEBUG:   Excon basics +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DEBUG:   Excon streaming basics #
DEBUG:   Excon basics (Basic Auth Pass) +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DEBUG:   Excon basics (Basic Auth Fail) +++
```
and when the test is disabled, the previous tests fail as well:
```
DEBUG: + shindont
DEBUG:
DEBUG:   Excon bad server interaction +++++
DEBUG:   Excon basics +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DEBUG:   Excon streaming basics #
DEBUG:   Excon basics (Basic Auth Pass) +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

Or in some previous run:
```
+ shindont
  
  Excon bad server interaction +++++  
  Excon basics +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  
  Excon streaming basics #  
  Excon basics (Basic Auth Pass) +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  
  Excon basics (Basic Auth Fail) +++  
  Excon basics (ssl) 
```

Note that we're running during package build for Fedora, so the environment is a bit modified.
(In case you're interested: It looks [like so](https://src.fedoraproject.org/rpms/rubygem-excon/blob/master/f/rubygem-excon.spec#_63).)

It may simply be a configuration issue, please advise.

**Comment by geemus** [comment] 2021-01-08 20:00
Thanks for the heads up and details. I'm not sure offhand on this one. We had some hangs in truffleruby reported for shindo more generally, which I think may have been fixed. Other than that nothing jumps immediately to mind (we haven't received any other similar issues that I'm aware of). Having it fail on different tests doesn't help narrow it down much either. Any ideas on how we might better pin down the issue at hand?

**Comment by pvalena** [comment] 2021-01-08 22:10
I can check which version which causes this.

**Comment by geemus** [comment] 2021-01-08 23:21
Sounds good, otherwise we might need to look at stack traces or other lower level details to try and pin it down.

**Comment by voxik** [comment] 2021-02-18 13:44
Just running the test suite several times, it always get stuck with the `Excon basics (ssl)` as a last entry. Moreover, this is the last run:

~~~
... snip ...

  Excon basics (ssl)
^C/usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:3:in `block in <top (required)>': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:65:in `join'
	from /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:65:in `run_in_thread'
	from /usr/share/gems/gems/shindo-0.3.8/lib/shindo/bin.rb:72:in `<top (required)>'
	from /usr/share/gems/gems/shindo-0.3.8/bin/shindo:5:in `require_relative'
	from /usr/share/gems/gems/shindo-0.3.8/bin/shindo:5:in `<top (required)>'
	from /usr/bin/shindo:23:in `load'
	from /usr/bin/shindo:23:in `<main>'
~~~

So there is likely some Shindo Ruby 3.0.0 incompatibility.

**Comment by voxik** [comment] 2021-02-18 13:46
> So there is likely some Shindo Ruby 3.0.0 incompatibility.

Going to try with Shindo 0.3.9 as there were some changes.

**Comment by voxik** [comment] 2021-02-18 16:51
~~~
$ rackup -s webrick --host 127.0.0.1 tests/rackups/ssl.ru 
/usr/share/gems/gems/rack-2.2.3/lib/rack/handler/webrick.rb:26:in `run': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /builddir/build/BUILD/excon-0.78.1/usr/share/gems/gems/excon-0.78.1/tests/rackups/ssl.ru:9:in `block in <main>'
	from /usr/share/gems/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	from /usr/share/gems/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	from /usr/share/gems/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	from /usr/share/gems/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	from /usr/share/gems/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /usr/share/gems/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	from /usr/share/gems/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	from /usr/share/gems/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
	from /usr/share/gems/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
	from /usr/share/gems/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
	from /usr/share/gems/gems/rack-2.2.3/lib/rack/server.rb:168:in `start'
	from /usr/share/gems/gems/rack-2.2.3/bin/rackup:5:in `<top (required)>'
	from /usr/bin/rackup:23:in `load'
	from /usr/bin/rackup:23:in `<main>'
~~~

**Comment by voxik** [comment] 2021-02-18 17:21
This is the fix so far:

~~~
$ git diff
diff --git a/tests/rackups/ssl.ru b/tests/rackups/ssl.ru
index fc17065..d825d2e 100644
--- a/tests/rackups/ssl.ru
+++ b/tests/rackups/ssl.ru
@@ -6,11 +6,11 @@ require File.join(File.dirname(__FILE__), 'basic')
 
 key_file = File.join(File.dirname(__FILE__), '..', 'data', '127.0.0.1.cert.key')
 cert_file = File.join(File.dirname(__FILE__), '..', 'data', '127.0.0.1.cert.crt')
-Rack::Handler::WEBrick.run(Basic, {
+Rack::Handler::WEBrick.run(Basic,
   :Port             => 9443,
   :SSLEnable        => true,
   :SSLPrivateKey    => OpenSSL::PKey::RSA.new(File.open(key_file).read),
   :SSLCertificate   => OpenSSL::X509::Certificate.new(File.open(cert_file).read),
   :SSLCACertificateFile => cert_file,
   :SSLVerifyClient  => OpenSSL::SSL::VERIFY_NONE,
-})
+)
diff --git a/tests/rackups/ssl_mismatched_cn.ru b/tests/rackups/ssl_mismatched_cn.ru
index d9c5edf..c4a8680 100644
--- a/tests/rackups/ssl_mismatched_cn.ru
+++ b/tests/rackups/ssl_mismatched_cn.ru
@@ -5,11 +5,11 @@ require 'webrick/https'
 require File.join(File.dirname(__FILE__), 'basic')
 key_file = File.join(File.dirname(__FILE__), '..', 'data', 'excon.cert.key')
 cert_file = File.join(File.dirname(__FILE__), '..', 'data', 'excon.cert.crt')
-Rack::Handler::WEBrick.run(Basic, {
+Rack::Handler::WEBrick.run(Basic,
   :Port             => 9443,
   :SSLEnable        => true,
   :SSLPrivateKey    => OpenSSL::PKey::RSA.new(File.open(key_file).read),
   :SSLCertificate   => OpenSSL::X509::Certificate.new(File.open(cert_file).read),
   :SSLCACertificateFile => cert_file,
   :SSLVerifyClient  => OpenSSL::SSL::VERIFY_NONE,
-})
+)
diff --git a/tests/rackups/ssl_verify_peer.ru b/tests/rackups/ssl_verify_peer.ru
index 44d64c7..c2025b6 100644
--- a/tests/rackups/ssl_verify_peer.ru
+++ b/tests/rackups/ssl_verify_peer.ru
@@ -5,7 +5,7 @@ require 'webrick/https'
 require File.join(File.dirname(__FILE__), 'basic')
 key_file = File.join(File.dirname(__FILE__), '..', 'data', 'excon.cert.key')
 cert_file = File.join(File.dirname(__FILE__), '..', 'data', 'excon.cert.crt')
-Rack::Handler::WEBrick.run(Basic, {
+Rack::Handler::WEBrick.run(Basic,
   :Port             => 8443,
   :SSLCertName      => [["CN", WEBrick::Utils::getservername]],
   :SSLEnable        => true,
@@ -13,4 +13,4 @@ Rack::Handler::WEBrick.run(Basic, {
   :SSLCertificate => OpenSSL::X509::Certificate.new(File.open(cert_file).read),
   :SSLCACertificateFile => cert_file,
   :SSLVerifyClient  => OpenSSL::SSL::VERIFY_PEER|OpenSSL::SSL::VERIFY_FAIL_IF_NO_PEER_CERT,
-})
+)
~~~

But there are more issues:

~~~
  Excon basics (reusable local port)
    has a local port + returns true
    local port can be re-bound - returns "xxxxxxxxxx"
    Cannot assign requested address - connect(2) for 127.0.0.1:9292 (Errno::EADDRNOTAVAIL)
      /builddir/build/BUILD/excon-0.78.1/usr/share/gems/gems/excon-0.78.1/tests/basic_tests.rb:322:in `connect'
      /builddir/build/BUILD/excon-0.78.1/usr/share/gems/gems/excon-0.78.1/tests/basic_tests.rb:322:in `connect'
      /builddir/build/BUILD/excon-0.78.1/usr/share/gems/gems/excon-0.78.1/tests/basic_tests.rb:362:in `block (3 levels) in <top (required)>'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo.rb:139:in `instance_eval'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo.rb:139:in `assert'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo.rb:111:in `returns'
      /builddir/build/BUILD/excon-0.78.1/usr/share/gems/gems/excon-0.78.1/tests/basic_tests.rb:354:in `block (2 levels) in <top (required)>'
      tests/test_helper.rb:250:in `with_rackup'
      /builddir/build/BUILD/excon-0.78.1/usr/share/gems/gems/excon-0.78.1/tests/basic_tests.rb:343:in `block in <top (required)>'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo.rb:79:in `instance_eval'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo.rb:79:in `tests'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo.rb:38:in `initialize'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo.rb:13:in `new'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo.rb:13:in `tests'
      /builddir/build/BUILD/excon-0.78.1/usr/share/gems/gems/excon-0.78.1/tests/basic_tests.rb:307:in `<top (required)>'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo/bin.rb:61:in `load'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo/bin.rb:61:in `block (2 levels) in run_in_thread'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo/bin.rb:58:in `each'
      /usr/share/gems/gems/shindo-0.3.9/lib/shindo/bin.rb:58:in `block in run_in_thread'
    Action? [c,q,r,?]? c
    
      
/usr/share/gems/gems/shindo-0.3.9/lib/shindo/bin.rb:83:in `<top (required)>': undefined method `join' for "[red]1 failed[/],, [red]1 errored[/], and [green]662 succeeded[/]in [bold]11.777175132830932[/] seconds":String (NoMethodError)
	from /usr/share/gems/gems/shindo-0.3.9/bin/shindo:5:in `require_relative'
	from /usr/share/gems/gems/shindo-0.3.9/bin/shindo:5:in `<top (required)>'
	from /usr/bin/shindo:23:in `load'
	from /usr/bin/shindo:23:in `<main>'
~~~

BTW I am testing with Ruby 3.0.0

**Comment by voxik** [comment] 2021-02-18 18:00
Hm, not sure, it might be bug in Ruby after all ...

**Comment by voxik** [comment] 2021-02-19 14:43
This might be the relevant strace output:

~~~
... snip ...

165   write(1, "    \33[1mlocal port can be re-bou"..., 39) = 39
165   write(1, " ", 1)                  = 1
165   mprotect(0x7fc85c485000, 32768, PROT_READ|PROT_WRITE) = 0
165   socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 8
165   fcntl(8, F_GETFD)                 = 0x1 (flags FD_CLOEXEC)
165   newfstatat(8, "", {st_mode=S_IFSOCK|0777, st_size=0, ...}, AT_EMPTY_PATH) = 0
165   getsockname(8, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("0.0.0.0")}, [2048->16]) = 0
165   setsockopt(8, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
165   setsockopt(8, SOL_SOCKET, SO_REUSEPORT, [1], 4) = 0
165   bind(8, {sa_family=AF_INET, sin_port=htons(41292), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
165   socket(AF_NETLINK, SOCK_RAW|SOCK_CLOEXEC, NETLINK_ROUTE) = 10
165   bind(10, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 0
165   getsockname(10, {sa_family=AF_NETLINK, nl_pid=164, nl_groups=00000000}, [12]) = 0
165   sendto(10, {{len=20, type=RTM_GETLINK, flags=NLM_F_REQUEST|NLM_F_DUMP, seq=1613744965, pid=0}, {ifi_family=AF_UNSPEC, ...}}, 20, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 20
165   recvmsg(10, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=1320, type=RTM_NEWLINK, flags=NLM_F_MULTI, seq=1613744965, pid=164}, {ifi_family=AF_UNSPEC, ifi_type=ARPHRD_LOOPBACK, ifi_index=if_nametoindex("lo"), ifi_flags=IFF_UP|IFF_LOOPBACK|IFF_RUNNING|IFF_LOWER_UP, ifi_change=0}, [{{nla_len=7, nla_type=IFLA_IFNAME}, "lo"}, {{nla_len=8, nla_type=IFLA_TXQLEN}, 1000}, {{nla_len=5, nla_type=IFLA_OPERSTATE}, 0}, {{nla_len=5, nla_type=IFLA_LINKMODE}, 0}, {{nla_len=8, nla_type=IFLA_MTU}, 65536}, {{nla_len=8, nla_type=IFLA_MIN_MTU}, 0}, {{nla_len=8, nla_type=IFLA_MAX_MTU}, 0}, {{nla_len=8, nla_type=IFLA_GROUP}, 0}, {{nla_len=8, nla_type=IFLA_PROMISCUITY}, 0}, {{nla_len=8, nla_type=IFLA_NUM_TX_QUEUES}, 1}, {{nla_len=8, nla_type=IFLA_GSO_MAX_SEGS}, 65535}, {{nla_len=8, nla_type=IFLA_GSO_MAX_SIZE}, 65536}, {{nla_len=8, nla_type=IFLA_NUM_RX_QUEUES}, 1}, {{nla_len=5, nla_type=IFLA_CARRIER}, 1}, {{nla_len=12, nla_type=IFLA_QDISC}, "noqueue"}, {{nla_len=8, nla_type=IFLA_CARRIER_CHANGES}, 0}, {{nla_len=8, nla_type=IFLA_CARRIER_UP_COUNT}, 0}, {{nla_len=8, nla_type=IFLA_CARRIER_DOWN_COUNT}, 0}, {{nla_len=5, nla_type=IFLA_PROTO_DOWN}, 0}, {{nla_len=36, nla_type=IFLA_MAP}, {mem_start=0, mem_end=0, base_addr=0, irq=0, dma=0, port=0}}, {{nla_len=10, nla_type=IFLA_ADDRESS}, 00:00:00:00:00:00}, {{nla_len=10, nla_type=IFLA_BROADCAST}, 00:00:00:00:00:00}, {{nla_len=196, nla_type=IFLA_STATS64}, {rx_packets=16955, tx_packets=16955, rx_bytes=142222364, tx_bytes=142222364, rx_errors=0, tx_errors=0, rx_dropped=0, tx_dropped=0, multicast=0, collisions=0, rx_length_errors=0, rx_over_errors=0, rx_crc_errors=0, rx_frame_errors=0, rx_fifo_errors=0, rx_missed_errors=0, tx_aborted_errors=0, tx_carrier_errors=0, tx_fifo_errors=0, tx_heartbeat_errors=0, tx_window_errors=0, rx_compressed=0, tx_compressed=0, rx_nohandler=0}}, {{nla_len=100, nla_type=IFLA_STATS}, {rx_packets=16955, tx_packets=16955, rx_bytes=142222364, tx_bytes=142222364, rx_errors=0, tx_errors=0, rx_dropped=0, tx_dropped=0, multicast=0, collisions=0, rx_length_errors=0, rx_over_errors=0, rx_crc_errors=0, rx_frame_errors=0, rx_fifo_errors=0, rx_missed_errors=0, tx_aborted_errors=0, tx_carrier_errors=0, tx_fifo_errors=0, tx_heartbeat_errors=0, tx_window_errors=0, rx_compressed=0, tx_compressed=0, rx_nohandler=0}}, {{nla_len=12, nla_type=IFLA_XDP}, {{nla_len=5, nla_type=IFLA_XDP_ATTACHED}, XDP_ATTACHED_NONE}}, {{nla_len=764, nla_type=IFLA_AF_SPEC}, [{{nla_len=136, nla_type=AF_INET}, {{nla_len=132, nla_type=IFLA_INET_CONF}, [[IPV4_DEVCONF_FORWARDING-1] = 1, [IPV4_DEVCONF_MC_FORWARDING-1] = 0, [IPV4_DEVCONF_PROXY_ARP-1] = 0, [IPV4_DEVCONF_ACCEPT_REDIRECTS-1] = 1, [IPV4_DEVCONF_SECURE_REDIRECTS-1] = 1, [IPV4_DEVCONF_SEND_REDIRECTS-1] = 1, [IPV4_DEVCONF_SHARED_MEDIA-1] = 1, [IPV4_DEVCONF_RP_FILTER-1] = 2, [IPV4_DEVCONF_ACCEPT_SOURCE_ROUTE-1] = 0, [IPV4_DEVCONF_BOOTP_RELAY-1] = 0, [IPV4_DEVCONF_LOG_MARTIANS-1] = 0, [IPV4_DEVCONF_TAG-1] = 0, [IPV4_DEVCONF_ARPFILTER-1] = 0, [IPV4_DEVCONF_MEDIUM_ID-1] = 0, [IPV4_DEVCONF_NOXFRM-1] = 1, [IPV4_DEVCONF_NOPOLICY-1] = 1, [IPV4_DEVCONF_FORCE_IGMP_VERSION-1] = 0, [IPV4_DEVCONF_ARP_ANNOUNCE-1] = 0, [IPV4_DEVCONF_ARP_IGNORE-1] = 0, [IPV4_DEVCONF_PROMOTE_SECONDARIES-1] = 1, [IPV4_DEVCONF_ARP_ACCEPT-1] = 0, [IPV4_DEVCONF_ARP_NOTIFY-1] = 0, [IPV4_DEVCONF_ACCEPT_LOCAL-1] = 0, [IPV4_DEVCONF_SRC_VMARK-1] = 0, [IPV4_DEVCONF_PROXY_ARP_PVLAN-1] = 0, [IPV4_DEVCONF_ROUTE_LOCALNET-1] = 0, [IPV4_DEVCONF_IGMPV2_UNSOLICITED_REPORT_INTERVAL-1] = 10000, [IPV4_DEVCONF_IGMPV3_UNSOLICITED_REPORT_INTERVAL-1] = 1000, [IPV4_DEVCONF_IGNORE_ROUTES_WITH_LINKDOWN-1] = 0, [IPV4_DEVCONF_DROP_UNICAST_IN_L2_MULTICAST-1] = 0, [IPV4_DEVCONF_DROP_GRATUITOUS_ARP-1] = 0, [IPV4_DEVCONF_BC_FORWARDING-1] = 0]}}, {{nla_len=624, nla_type=AF_INET6}, [{{nla_len=8, nla_type=IFLA_INET6_FLAGS}, IF_READY}, {{nla_len=20, nla_type=IFLA_INET6_CACHEINFO}, {max_reasm_len=65535, tstamp=121827178, reachable_time=38532, retrans_time=1000}}, {{nla_len=212, nla_type=IFLA_INET6_CONF}, [[DEVCONF_FORWARDING] = 0, [DEVCONF_HOPLIMIT] = 64, [DEVCONF_MTU6] = 65536, [DEVCONF_ACCEPT_RA] = 1, [DEVCONF_ACCEPT_REDIRECTS] = 1, [DEVCONF_AUTOCONF] = 1, [DEVCONF_DAD_TRANSMITS] = 1, [DEVCONF_RTR_SOLICITS] = -1, [DEVCONF_RTR_SOLICIT_INTERVAL] = 4000, [DEVCONF_RTR_SOLICIT_DELAY] = 1000, [DEVCONF_USE_TEMPADDR] = -1, [DEVCONF_TEMP_VALID_LFT] = 604800, [DEVCONF_TEMP_PREFERED_LFT] = 86400, [DEVCONF_REGEN_MAX_RETRY] = 3, [DEVCONF_MAX_DESYNC_FACTOR] = 600, [DEVCONF_MAX_ADDRESSES] = 16, [DEVCONF_FORCE_MLD_VERSION] = 0, [DEVCONF_ACCEPT_RA_DEFRTR] = 1, [DEVCONF_ACCEPT_RA_PINFO] = 1, [DEVCONF_ACCEPT_RA_RTR_PREF] = 1, [DEVCONF_RTR_PROBE_INTERVAL] = 60000, [DEVCONF_ACCEPT_RA_RT_INFO_MAX_PLEN] = 0, [DEVCONF_PROXY_NDP] = 0, [DEVCONF_OPTIMISTIC_DAD] = 0, [DEVCONF_ACCEPT_SOURCE_ROUTE] = 0, [DEVCONF_MC_FORWARDING] = 0, [DEVCONF_DISABLE_IPV6] = 0, [DEVCONF_ACCEPT_DAD] = -1, [DEVCONF_FORCE_TLLAO] = 0, [DEVCONF_NDISC_NOTIFY] = 0, [DEVCONF_MLDV1_UNSOLICITED_REPORT_INTERVAL] = 10000, [DEVCONF_MLDV2_UNSOLICITED_REPORT_INTERVAL] = 1000, ...]}, {{nla_len=300, nla_type=IFLA_INET6_STATS}, [[IPSTATS_MIB_NUM] = 37, [IPSTATS_MIB_INPKTS] = 99, [IPSTATS_MIB_INOCTETS] = 8904, [IPSTATS_MIB_INDELIVERS] = 99, [IPSTATS_MIB_OUTFORWDATAGRAMS] = 0, [IPSTATS_MIB_OUTPKTS] = 99, [IPSTATS_MIB_OUTOCTETS] = 8904, [IPSTATS_MIB_INHDRERRORS] = 0, [IPSTATS_MIB_INTOOBIGERRORS] = 0, [IPSTATS_MIB_INNOROUTES] = 0, [IPSTATS_MIB_INADDRERRORS] = 0, [IPSTATS_MIB_INUNKNOWNPROTOS] = 0, [IPSTATS_MIB_INTRUNCATEDPKTS] = 0, [IPSTATS_MIB_INDISCARDS] = 0, [IPSTATS_MIB_OUTDISCARDS] = 0, [IPSTATS_MIB_OUTNOROUTES] = 0, [IPSTATS_MIB_REASMTIMEOUT] = 0, [IPSTATS_MIB_REASMREQDS] = 0, [IPSTATS_MIB_REASMOKS] = 0, [IPSTATS_MIB_REASMFAILS] = 0, [IPSTATS_MIB_FRAGOKS] = 0, [IPSTATS_MIB_FRAGFAILS] = 0, [IPSTATS_MIB_FRAGCREATES] = 0, [IPSTATS_MIB_INMCASTPKTS] = 0, [IPSTATS_MIB_OUTMCASTPKTS] = 0, [IPSTATS_MIB_INBCASTPKTS] = 0, [IPSTATS_MIB_OUTBCASTPKTS] = 0, [IPSTATS_MIB_INMCASTOCTETS] = 0, [IPSTATS_MIB_OUTMCASTOCTETS] = 0, [IPSTATS_MIB_INBCASTOCTETS] = 0, [IPSTATS_MIB_OUTBCASTOCTETS] = 0, [IPSTATS_MIB_CSUMERRORS] = 0, ...]}, {{nla_len=52, nla_type=IFLA_INET6_ICMP6STATS}, [[ICMP6_MIB_NUM] = 6, [ICMP6_MIB_INMSGS] = 0, [ICMP6_MIB_INERRORS] = 0, [ICMP6_MIB_OUTMSGS] = 0, [ICMP6_MIB_OUTERRORS] = 0, [ICMP6_MIB_CSUMERRORS] = 0]}, {{nla_len=20, nla_type=IFLA_INET6_TOKEN}, inet_pton(AF_INET6, "::")}, {{nla_len=5, nla_type=IFLA_INET6_ADDR_GEN_MODE}, IN6_ADDR_GEN_MODE_EUI64}]}]}]}, iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 1320
165   recvmsg(10, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=20, type=NLMSG_DONE, flags=NLM_F_MULTI, seq=1613744965, pid=164}, 0}, iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 20
165   sendto(10, {{len=20, type=RTM_GETADDR, flags=NLM_F_REQUEST|NLM_F_DUMP, seq=1613744966, pid=0}, {ifa_family=AF_UNSPEC, ...}}, 20, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 20
165   recvmsg(10, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=76, type=RTM_NEWADDR, flags=NLM_F_MULTI, seq=1613744966, pid=164}, {ifa_family=AF_INET, ifa_prefixlen=8, ifa_flags=IFA_F_PERMANENT, ifa_scope=RT_SCOPE_HOST, ifa_index=if_nametoindex("lo")}, [{{nla_len=8, nla_type=IFA_ADDRESS}, inet_addr("127.0.0.1")}, {{nla_len=8, nla_type=IFA_LOCAL}, inet_addr("127.0.0.1")}, {{nla_len=7, nla_type=IFA_LABEL}, "lo"}, {{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_PERMANENT}, {{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=4294967295, ifa_valid=4294967295, cstamp=121827178, tstamp=121827178}}]}, iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 76
165   recvmsg(10, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=72, type=RTM_NEWADDR, flags=NLM_F_MULTI, seq=1613744966, pid=164}, {ifa_family=AF_INET6, ifa_prefixlen=128, ifa_flags=IFA_F_PERMANENT, ifa_scope=RT_SCOPE_HOST, ifa_index=if_nametoindex("lo")}, [{{nla_len=20, nla_type=IFA_ADDRESS}, inet_pton(AF_INET6, "::1")}, {{nla_len=20, nla_type=IFA_CACHEINFO}, {ifa_prefered=4294967295, ifa_valid=4294967295, cstamp=121827178, tstamp=121827178}}, {{nla_len=8, nla_type=IFA_FLAGS}, IFA_F_PERMANENT}]}, iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 72
165   recvmsg(10, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=20, type=NLMSG_DONE, flags=NLM_F_MULTI, seq=1613744966, pid=164}, 0}, iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 20
165   close(10)                         = 0
165   connect(8, {sa_family=AF_INET, sin_port=htons(9292), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EADDRNOTAVAIL (Cannot assign requested address)
165   ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
165   write(1, "\33[31m- returns \"xxxxxxxxxx\"\33[0m\n", 32) = 32

... snip ...
~~~

**Comment by geemus** [comment] 2021-02-21 13:27
Thanks, I've merged your other patches, so hopefully we are getting closer at least.

**Comment by voxik** [comment] 2021-03-02 09:51
I think this should be closed and the remaining issue should be tracked separately, because it seems to be related to systemd-nsawn and it very likely not reproducible on bare metal

**Comment by geemus** [comment] 2021-03-02 14:42
Sounds good, closing.

**Closed by geemus** 2021-03-02 14:42 UTC
