### ISSUE TITLE
Is the new logging broken?

### ISSUE THREAD

**Issue by djberg96** [excon/excon#663] opened 2018-02-06 21:44 UTC
Did I not test my own logging PR thoroughly enough? This doesn't seem to work:

```
require 'excon'
require 'logger'

url = 'http://www.google.com'
log = Logger.new('temp.log')

connection = Excon.new(url, :logger => log)
connection.get
```
The log file is created, but there's no output from the request.

However, this approach works as expected:

```
Excon::LoggingInstrumentor.logger = log
connection = Excon.new(url, :instrumentor => Excon::LoggingInstrumentor)
```

What did I do wrong?

**Comment by geemus** [comment] 2018-02-07 15:28
Not sure, it seems like `logger=` does basically the same as what you do in the second example:
https://github.com/excon/excon/blob/master/lib/excon/connection.rb#L40

Actually, I think it is a timing issue. Passing logger argument to initialize doesn't inherently call `logger=`. I suspect this would work:

```ruby
connection = Excon.new(url)
connection.logger = log
connection.get
```

I think we could fix it by adding something that uses a logger argument in initialize (if available) to call `logger=`. Does that make sense?

**Comment by djberg96** [comment] 2018-02-08 20:50
Yes, that makes sense. I thought I already did, but I guess not.

**Comment by geemus** [comment] 2018-02-08 21:03
Yeah, I thought we were pretty thorough. Guess it could be pretty easy to miss though, at least it should be fairly easy to fix.

**Comment by djberg96** [comment] 2018-02-22 22:17
@geemus The other thing I was wondering is if we can dupe the singleton instrumentor for logging so that each connection can have it's own log. For example, this doesn't work as I had hoped, and everything gets logged to the same file (file2.txt):

```
require 'excon'
require 'logger'

url1 = 'http://www.google.com'
url2 = 'http://www.ruby-lang.org'

log1 = Logger.new('file1.txt')
log2 = Logger.new('file2.txt')

connection1 = Excon.new(url1)
connection1.logger = log1

connection2 = Excon.new(url2)
connection2.logger = log2

connection1.get
connection2.get
```

Otherwise the logger is only useful for debugging, and each project will have to write its own logging instrumentor anyway. Not a *huge* deal, but it does sort of defeat my goals a bit.

**Comment by geemus** [comment] 2018-02-26 16:27
It should be doable, but we may actually need to rethink the interface a little to make it work as we want. The class is used for instrumentors/other middlewares, because each request will create new instances to use. I think a better approach might actually be to have a `logger` key in datum, and have the intstrumentor look for and use that value? I think that you would then be able to do the following to achieve what you wanted:

```ruby
require 'excon'
require 'logger'

url1 = 'http://www.google.com'
url2 = 'http://www.ruby-lang.org'

log1 = Logger.new('file1.txt')
log2 = Logger.new('file2.txt')

connection1 = Excon.new(url1, logger: log1)
connection2 = Excon.new(url2, logger: log2)

connection1.get
connection2.get
```

I think to get that working we would want to call an assignment related thing similar to what was discussed above to add the logging instrumentor to the middlewares, then the middleware itself would look at the datum to find it's logger argument. What do you think?

**Comment by djberg96** [comment] 2018-02-26 19:21
@geemus Unfortunately, I think I'm at a point where I can't intelligently comment because I don't know the design well enough.

I would say test out the approach that you mentioned, and if it works without causing issues for the current instrumentors, then please implement it. :)

**Comment by geemus** [comment] 2018-02-27 14:46
@djberg96 fair enough, thanks for working through it as much as you already have. I think I have a pretty good idea of how we can get what you want and tweak the interface to bring it a bit more inline with other usage. I'll try to sneak some time in to do a PR soon.

**Comment by geemus** [comment] 2018-03-06 19:59
@djberg96 I think this gets us a good part of the way toward what I meant anyway: https://github.com/excon/excon/commit/7771c2b5f6bf8571111a68a900734c5913926e59

Given that we were surprised here though, it may be that we need better test coverage to ensure extra logger settings are used appropriately? Does this make more sense now? Thoughts?

**Comment by djberg96** [comment] 2018-03-06 20:24
@geemus That looks good. As for specs, I agree. I'm hoping you'll write them, though, because I'm lazy. ;)

Did you already try this out with general futzing?

**Comment by geemus** [comment] 2018-03-07 15:12
I ran the existing tests, but did not do subsequent futzing. Can see about fixing up tests/etc next. One thing I might note is that I was pondering deprecating the logger/logger= methods. Since the params blob is now used instead, they are somewhat redundant and inconsistent with other params. Thoughts?

**Comment by djberg96** [comment] 2018-03-07 15:39
Yeah, I would just remove those. Technically an API break, but this will have been a short lived thing.

**Comment by djberg96** [comment] 2018-03-15 16:51
@geemus I tried this and it did not work. The log files are generated, but nothing is written to them. It's like the instrumentor isn't getting set.

```
$:.unshift 'lib'
require 'excon'
require 'logger'

p Excon::VERSION

url1 = 'http://www.google.com'
url2 = 'http://www.ruby-lang.org'

log1 = Logger.new('file1.txt')
log2 = Logger.new('file2.txt')

connection1 = Excon.new(url1, logger: log1)
connection2 = Excon.new(url2, logger: log2)

p connection1.logger # nil
p connection2.logger # nil

connection1.get
connection2.get
```

**Comment by djberg96** [comment] 2018-03-22 19:51
@geemus That only seems to work for requests, but not responses. Try removing the `|| Logger.new($stderr)` from the instrumentor to see what I mean.

**Comment by geemus** [comment] 2018-03-26 15:14
Thanks for digging deeper, I still need to do more thorough testing around this (have just been struggling to find time+focus). Looks like the issue is a discrepancy between instrumentor params for request and response. Request gets the whole datum, response only gets the response datum :(. I don't think that was entirely on purpose, but will take a little bit of effort to make them consistent without breaking backwards compatibility. I'll see if I can't cook something up shortly. Thanks again for your patience and continuing to work through this with me. I think/hope we are nearly there now.

**Comment by djberg96** [comment] 2018-04-04 13:10
@geemus Any luck?

**Comment by geemus** [comment] 2018-04-05 20:48
@djberg96 thanks for checking in. Pretty sure I know what I want to do here, have just had a lot of unrelated things going on which have made it hard to put together enough contiguous time to get it sorted out. Hopefully I can fix that soon though.

**Comment by djberg96** [comment] 2018-04-08 04:58
@geemus Where is it?

**Comment by geemus** [comment] 2018-04-08 16:29
Oops, that would certainly help, see: https://github.com/excon/excon/tree/logger-datum (or more specifically: https://github.com/excon/excon/commit/a1567ceb6bc3a92882d3dbdad0220f66f11a5203

**Comment by djberg96** [comment] 2018-04-08 18:16
Doesn't seem to work, but now it's not logging *anything* to the log files. I'm not sure what's happening now.

**Comment by geemus** [comment] 2018-04-10 14:51
Strange, it seems to log as I would expect to the two files. I'll try to dig deeper and add explicit tests soon, as I think/hope this is more or less on track now.

**Comment by djberg96** [comment] 2018-04-10 16:00
Maybe it's just my local setup, and I've got something messed up. If you see it working, and you have tests to prove it, then I'll just go along with it. :)

**Comment by djberg96** [comment] 2018-04-22 17:13
I still can't get this to work. I made sure to fetch & merge the latest from master, and removed any excon gems that were already installed. I still don't see anything being logged to the logger files. I'm just using the script I pasted above.

**Comment by djberg96** [comment] 2018-05-14 19:09
@geemus If it's working for you, and passing the tests, then I would say that it must be an issue for me and proceed.

**Comment by geemus** [comment] 2018-05-21 19:16
@djberg96 went ahead and merged the related branch, the passing test should show that it is working, if I'm not mistaken. Do let me know if you continue to have issue though and we can iterate further (it could probably use additional tests either way, when one of us gets a chance). Thanks!

**Closed by geemus** 2018-05-21 19:16 UTC

**Comment by djberg96** [comment] 2018-05-22 21:33
@geemus ok, once I actually specified the `:instrumentor` then it worked. If you don't specify one, it just sort of does nothing. We should probably raise an error in that case, but that can be a separate issue.

**Comment by geemus** [comment] 2018-05-22 21:34
@djberg96 glad to hear it. Yeah, if you want to submit an issue that shows what you called that silently failed then we can work backwards from that to get the right error and things. Thank you for working through it all with me and also being patient!
